language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev" 
install:
  - pip install -r requirements-tests.txt
script:
  - pytest --cov pycommand_bus/
  - mypy tests/ pycommand_bus/
  - pycodestyle --max-line-length=120 tests/ pycommand_bus/

