language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev" 
install:
  - pip install -r requirements-tests.txt
script:
  - pytest --cov pybuses/
  - mypy tests/ pybuses/ examples/
  - pycodestyle --max-line-length=120 tests/ pybuses/ examples/
  - coveralls

